import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Slider from '../components/Slider'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Responsive - Slider</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, intial scale=1"/>
      </Head>
      
        <Slider/>
     
    </div>
  )
}
